# GitHub Pages 網站設定檔

# ----------------------------------------------------
# 防止檔案被忽略的設定 (如果使用 Jekyll)
# ----------------------------------------------------

# 將需要部署但不是標準 Jekyll 檔案的項目列在 include: 之下
# 這裡明確指示 Jekyll 包含 sitemap.xml
include:
  - sitemap.xml

# ----------------------------------------------------
# [可選] 如果您想設定主題、標題等，可以加在這邊
# ----------------------------------------------------
# title: 您的網站標題
# description: 您的網站描述
